// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATskMsiiEYRoTZPY67lzl1kzsoPl624aQ',
    appId: '1:796083786066:web:2cbb388923836068c52a8b',
    messagingSenderId: '796083786066',
    projectId: 'stafftreport-7229f',
    authDomain: 'stafftreport-7229f.firebaseapp.com',
    storageBucket: 'stafftreport-7229f.firebasestorage.app',
    measurementId: 'G-SRSKWPVSSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC68SVAcSqqWKrrZmZEP7LJTLnMHwWFrq8',
    appId: '1:796083786066:android:8ffcdb429aad0d8fc52a8b',
    messagingSenderId: '796083786066',
    projectId: 'stafftreport-7229f',
    storageBucket: 'stafftreport-7229f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZUCvBAyttVbisubiGGbfm2yVOug6p8Dg',
    appId: '1:796083786066:ios:cd4176f2415471f0c52a8b',
    messagingSenderId: '796083786066',
    projectId: 'stafftreport-7229f',
    storageBucket: 'stafftreport-7229f.firebasestorage.app',
    iosBundleId: 'com.example.staffPerformanceMapping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZUCvBAyttVbisubiGGbfm2yVOug6p8Dg',
    appId: '1:796083786066:ios:cd4176f2415471f0c52a8b',
    messagingSenderId: '796083786066',
    projectId: 'stafftreport-7229f',
    storageBucket: 'stafftreport-7229f.firebasestorage.app',
    iosBundleId: 'com.example.staffPerformanceMapping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATskMsiiEYRoTZPY67lzl1kzsoPl624aQ',
    appId: '1:796083786066:web:353c83bf23fb84bbc52a8b',
    messagingSenderId: '796083786066',
    projectId: 'stafftreport-7229f',
    authDomain: 'stafftreport-7229f.firebaseapp.com',
    storageBucket: 'stafftreport-7229f.firebasestorage.app',
    measurementId: 'G-NVVG95QX09',
  );

}